### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by wlonglee** [Longri/libgdx_SqLiteDB#6]
Caused by: java.lang.UnsatisfiedLinkError: de.longri.gdx.sqlite.GdxSqlite.getGdxSqliteVersion()Ljava/lang/String;
	at de.longri.gdx.sqlite.GdxSqlite.getGdxSqliteVersion(Native Method)
	at de.longri.gdx.sqlite.GdxSqlite.<clinit>(GdxSqlite.java:42)

**Comment by wlonglee** [comment]
Running a desktop application reports this error，I don't know why

**Comment by Longri** [comment]
have you added the native dependencies for Desktop?

**Comment by wlonglee** [comment]
buildscript {


    repositories {
//        mavenLocal()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0'
    }
}

allprojects {
    apply plugin: "eclipse"
    apply plugin: "idea"

    version = '1.0'
    ext {
        appName = "leeGame"
        gdxVersion = '1.9.8'
        roboVMVersion = '2.3.3'
        box2DLightsVersion = '1.4'
        ashleyVersion = '1.7.0'
        aiVersion = '1.8.0'
        gdxSqliteVersion = '0.6.7-SNAPSHOT'
    }

    repositories {
//        mavenLocal()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
    }
}

project(":desktop") {
    apply plugin: "java"


    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
        compile "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"

        compile "de.longri.gdx-sqlite:gdx-sqlite-platform:$gdxSqliteVersion:natives-desktop"
    }
}

project(":android") {
    apply plugin: "android"

    configurations { natives }

    dependencies {
        compile project(":core")
        compile "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-arm64-v8a"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86"
        natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86_64"
        compile "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
        natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-armeabi"
        natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-armeabi-v7a"
        natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-arm64-v8a"
        natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-x86"
        natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-x86_64"

        compile "de.longri.gdx-sqlite:gdx-sqlite:$gdxSqliteVersion"
        natives "de.longri.gdx-sqlite:gdx-sqlite-platform:$gdxSqliteVersion:natives-armeabi"
        natives "de.longri.gdx-sqlite:gdx-sqlite-platform:$gdxSqliteVersion:natives-armeabi-v7a"
        natives "de.longri.gdx-sqlite:gdx-sqlite-platform:$gdxSqliteVersion:natives-arm64-v8a"
        natives "de.longri.gdx-sqlite:gdx-sqlite-platform:$gdxSqliteVersion:natives-x86"
        natives "de.longri.gdx-sqlite:gdx-sqlite-platform:$gdxSqliteVersion:natives-x86_64"
    }
}

project(":core") {
    apply plugin: "java"


    dependencies {
        compile "com.badlogicgames.gdx:gdx:$gdxVersion"
        compile "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"

        compile "de.longri.gdx-sqlite:gdx-sqlite:$gdxSqliteVersion"
    }
}

tasks.eclipse.doLast {
    delete ".project"
}

**Comment by wlonglee** [comment]
This is my project configuration,Whether the project needs NDK ？
